// <auto-generated />
using System;
using FinOps.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FinOps.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(FinOpsDbContext))]
    [Migration("20260612224510_AddCloudCostDaily")]
    partial class AddCloudCostDaily
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FinOps.Domain.CloudResources.CloudResource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("account_id");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen_at");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("provider");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("region");

                    b.Property<string>("ResourceGroup")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("resource_group");

                    b.Property<string>("ResourceId")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("resource_id");

                    b.Property<string>("ResourceIdNormalized")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("resource_id_normalized");

                    b.Property<string>("ResourceName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("resource_name");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("resource_type");

                    b.Property<string>("TagsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("tags_json");

                    b.HasKey("Id");

                    b.HasIndex("Provider", "ResourceIdNormalized")
                        .IsUnique()
                        .HasDatabaseName("ux_cloud_resources_provider_resource_id");

                    b.ToTable("cloud_resources", (string)null);
                });

            modelBuilder.Entity("FinOps.Domain.Costs.CloudCostDaily", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("account_id");

                    b.Property<decimal>("Cost")
                        .HasPrecision(20, 8)
                        .HasColumnType("numeric(20,8)")
                        .HasColumnName("cost");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("currency");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("provider");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_json");

                    b.Property<string>("ResourceGroup")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("resource_group");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("service_name");

                    b.Property<DateOnly>("UsageDate")
                        .HasColumnType("date")
                        .HasColumnName("usage_date");

                    b.HasKey("Id");

                    b.HasIndex("Provider", "AccountId", "UsageDate", "ServiceName", "ResourceGroup", "Currency")
                        .IsUnique()
                        .HasDatabaseName("ux_cloud_cost_daily_identity");

                    b.ToTable("cloud_cost_daily", (string)null);
                });

            modelBuilder.Entity("FinOps.Domain.Etl.EtlJobRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("error_message");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<string>("JobName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("job_name");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("provider");

                    b.Property<int>("RecordsProcessed")
                        .HasColumnType("integer")
                        .HasColumnName("records_processed");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("JobName", "StartedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_etl_job_runs_job_name_started_at");

                    b.ToTable("etl_job_runs", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
